# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# +001 DOWNLOAD DATA
# +002 PREPARE & READ  DATA
#      1.1.a.4 - Total biomass supply for food purposes, including inputs                        - 1000 T of Dry Matter (net trade)/capita * 1000
#      1.1.a.5 - Biomass directly consumed by humans by source (animal, fish, plant-based, algae)- 1000 T of dry matter (Net trade)/capita * 1000
#      2.3.a.1 - Biomass production in EU from primary production sectors (agriculture, forests, fisheries, algae, waste): Missing data
#      3.1.a.1 - Domestic Material Consumption (Biomass) per capita                              - (1000 Tonnes/capita) * 1000 
#      3.1.a.2 - Material footprint (Biomass)                                                    - Tonne per capita
#      3.1.b.1 - Energy productivity                                                             - eur/kg of oil equivalent 
#      3.1.b.2 - Share of renewable energy in gross final energy consumption                     - Percent (%) 
#      3.1.c.2 - Circular material rate                                                          - Percent (% of total material use)
#      3.4.a.2 - Total biomass consumed for energy                                               - 1000 T of Dry Matter/capita * 1000
#      3.4.a.3 - Total biomass consumed for materials                                            - 1000 T of Dry Matter/capita * 1000
#      3.1.c.3 - Final Energy Consumption from renewable municipal waste                         - follow up needed
#      3.1.c.4 - Recycling rate of bio-waste                                                     - Kilograms/capita
#      3.1.c.5 - Biowaste generated by source                                                    - Kg_dry/capita * 1000
#      3.1.c.6 - Biowaste recovered by source                                                    - Kg_dry/capita * 1000
#      3.4.b.1 - Liquid biofuels production (bioethanol, pure biogasoline, biodiesel, bio jet kerosene and other liquid biofuels)
#                                                                                                - Thousand tonnes per year/capita *1000 
#      3.4.b.2 - Biogasses (indigenous) production                                               - TERAJOULE/capita *1000
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# +001 DOWNLOAD DATA
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  
# Some data are available on the Bitbucket repositoty (see below), others need to be downloaded manually
# BitBucket repository : Bioeconomy Knowledge Centre / biomon-data
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#clone repository
#on the command prompt:
#git clone https://citnet.tech.ec.europa.eu/CITnet/stash/scm/beo/biomon-data.git
#cd folder-in-which-you-download-data
#git checkout --track origin/develop

# ++++ DOWNLOAD POPULATION NUMBERS PER COUNTRY
# ++++ The aim is to create intensive indicators that can be compared to one another
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# We first have to create a dataframe with the names of the countries of interest
# because it is used in the following manipulations and creations
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
geo       <- c('Belgium','Bulgaria','Czechia','Denmark','Germany','Estonia','Ireland','Greece','Spain','France','Croatia',
              'Italy','Cyprus','Latvia','Lithuania','Luxembourg','Hungary','Malta','Netherlands','Austria','Poland','Portugal',
              'Romania','Slovenia','Slovakia','Finland','Sweden','United Kingdom')

geo_code  <- c('BE','BG','CZ','DK','DE','EE','IE','EL','ES','FR','HR',
              'IT','CY','LV','LT','LU','HU','MT','NL','AT','PL','PT',
              'RO','SI','SK','FI','SE','UK')

countries <- data.frame(geo,
                        geo_code, 
                        stringsAsFactors=FALSE) 

#Population on 1 January by age and sex
#https://ec.europa.eu/eurostat/databrowser/view/demo_pjan/default/table?lang=en 
#The data retreived from Eurostat must be reorganized first - done with python in this case 

pop_csv           <- read.csv(paste0(cordir_in,"demo_pjan_1_Data.csv"), stringsAsFactors = FALSE)
names(pop_csv)
names(pop_csv)[1] <- "geo"
names(pop_csv)[2] <- "time"
names(pop_csv)[3] <- "population"

pop_csv$population <- as.numeric(gsub(",","",pop_csv$population))

pop_csv <- pop_csv %>% 
  full_join(countries,by=c("geo"))
pop_csv$geo_code[which(grepl("Germany including former GDR",pop_csv$geo))]  <- "DE" 

#only keep the lines that correspond to a geo_code. It is the countries of interest
pop_csv <- pop_csv %>%
  filter(geo_code != "NA")

#create new table with n+1
pop_csv_n1           <- read.csv(paste0(cordir_in,"demo_pjan_1_Data.csv"), stringsAsFactors = FALSE)
names(pop_csv_n1)

names(pop_csv_n1)[1] <- "geo"
names(pop_csv_n1)[2] <- "time"
names(pop_csv_n1)[3] <- "population"
names(pop_csv_n1)
pop_csv_n1$population <- as.numeric(gsub(",","",pop_csv_n1$population))
levels(as.factor(pop_csv_n1$time))

# filter to have the data corresponding to the year n+1 and above 
pop_csv_n1 <- pop_csv_n1 %>%
  filter(time != "2000") 
#except that we need to have the same years to do the full_join
#so trick : we say that the values correspond to the year n and above (but it actually correspond to n+1)
pop_csv_n1$time  <- pop_csv_n1$time -1

pop_csv_n1 <- pop_csv_n1 %>% 
  full_join(pop_csv,by=c("geo","time"))

#we re-establish the correct years by creating a new column n+1 once we have done the join
pop_csv_n1$time_n_1  <- pop_csv_n1$time +1

# population.x corresponds to 'time'
# population.y corresponds to 'time_n_1'

#compute the arithmetic mean of the population of two consecutive years
pop_csv_n1$mean_population <- (pop_csv_n1$population.x + pop_csv_n1$population.y)/2

#only keep the lines that correspond to a geo_code. It is the countries of interest
pop_csv_n1 <- pop_csv_n1 %>%
  filter(geo_code != "NA")

# +002 PREPARE & READ  DATA
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++  

# - 1.1.a.4 - Total biomass supply for food purposes, including inputs - 1000 T of Dry Matter (net trade)/capita * 1000
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
tot_biomass <- read.csv(paste0(cordir_in,"output_data/indicators/1.1.a.4/1.1.a.4.csv"), stringsAsFactors = FALSE)
tot_biomass
names(tot_biomass)
names(tot_biomass)[3] <- "tot_biomass"
names(tot_biomass)[4] <- "unit.tot_biomass"

unique(tot_biomass$geo_code)
options(max.print = 1000 * ncol(tot_biomass))
tot_biomass <- tot_biomass %>%
  filter(geo_code != "EU27_2020" & geo_code != "EU28") 

levels(as.factor(tot_biomass$unit.tot_biomass))

#create a new column to get an intensive indicator
tot_biomass <- tot_biomass %>% 
  full_join(pop_csv_n1,by=c("time", "geo_code"))

tot_biomass <- tot_biomass[!(tot_biomass$geo_code=="NA"),]

tot_biomass$value_per_capita <- tot_biomass$tot_biomass / tot_biomass$mean_population
# units= 1000 T of dry matter/population
# if we multiply by 1000 -> Megatonne of Dry matter /capita
tot_biomass$value_per_capita <- tot_biomass$value_per_capita*1000

names(tot_biomass)[7] <- "tot_biomass_capita"
#Order by alphabet 
tot_biomass <- tot_biomass[order(tot_biomass$geo_code),]

# Only consider the years and countries for which there is data
tot_biomass <- tot_biomass %>%
  filter(value_per_capita != "NA") 

# - 1.1.a.5 - Biomass directly consumed by humans by source (animal, fish, plant-based, algae) - 1000 T of dry matter (Net trade)/capita * 1000
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# animal - 1000 T of dry matter (Net trade)/capita
# Missing values /!\ Values only available for AT,BE,BG,CY,CZ,DK,EE,FI,HR
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
biomass_animal <- read.csv(paste0(cordir_in,"output_data/indicators/1.1.a.5/1.1.a.5_animal.csv"), stringsAsFactors = FALSE)
head(biomass_animal)
names(biomass_animal)
biomass_animal <- biomass_animal[-c(3:8)]
names(biomass_animal)[1] <- "geo"
names(biomass_animal)[2] <- "time"
names(biomass_animal)[3] <- "unit"
names(biomass_animal)[4] <- "value"

biomass_animal <- biomass_animal %>% 
  full_join(countries,by=c("geo"))

levels(as.factor(biomass_animal$unit))

#create a new column ("/capita") to get an intensive indicator
biomass_animal <- biomass_animal %>% 
  full_join(pop_csv_n1,by=c("time", "geo_code"))

biomass_animal <- biomass_animal[!(biomass_animal$geo_code=="NA"),]

biomass_animal$value_per_capita <- biomass_animal$value / biomass_animal$mean_population
# units= 1000 T of dry matter/person
biomass_animal$value_per_capita <- biomass_animal$value_per_capita*1000

#Order by alphabet 
biomass_animal <- biomass_animal[order(biomass_animal$geo_code),]
biomass_animal <- biomass_animal[-c(6:9)]

# Only consider the years and countries for which there is data
biomass_animal <- biomass_animal %>%
  filter(value_per_capita != "NA") 

# fish - 1000 T of dry matter (Net trade)/capita
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
biomass_fish <- read.csv(paste0(cordir_in,"output_data/indicators/1.1.a.5/1.1.a.5_fish.csv"), stringsAsFactors = FALSE)
head(biomass_fish)
names(biomass_fish)
biomass_fish <- biomass_fish[-c(3:8)]
names(biomass_fish)[1] <- "geo"
names(biomass_fish)[2] <- "time"
names(biomass_fish)[3] <- "unit"
names(biomass_fish)[4] <- "value"

biomass_fish <- biomass_fish %>% 
  full_join(countries,by=c("geo"))

levels(as.factor(biomass_fish$unit))

#create a new column ("/capita") to get an intensive indicator
biomass_fish <- biomass_fish %>% 
  full_join(pop_csv_n1,by=c("time", "geo_code"))

biomass_fish <- biomass_fish[!(biomass_fish$geo_code=="NA"),]

biomass_fish$value_per_capita <- biomass_fish$value / biomass_fish$mean_population
# units= 1000 T of dry matter/person
biomass_fish$value_per_capita <- biomass_fish$value_per_capita*1000

#Order by alphabet 
biomass_fish <- biomass_fish[order(biomass_fish$geo_code),]
biomass_fish <- biomass_fish[-c(6:9)]

# Only consider the years and countries for which there is data
biomass_fish <- biomass_fish %>%
  filter(value_per_capita != "NA") 

# plant - 1000 T of dry matter (Net trade)/capita
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
biomass_plant <- read.csv(paste0(cordir_in,"output_data/indicators/1.1.a.5/1.1.a.5_plant.csv"), stringsAsFactors = FALSE)
head(biomass_plant)
names(biomass_plant)
biomass_plant <- biomass_plant[-c(3:8)]
names(biomass_plant)[1] <- "geo"
names(biomass_plant)[2] <- "time"
names(biomass_plant)[3] <- "unit"
names(biomass_plant)[4] <- "value"

biomass_plant <- biomass_plant %>% 
  full_join(countries,by=c("geo"))

levels(as.factor(biomass_plant$unit))

#create a new column ("/capita") to get an intensive indicator
biomass_plant <- biomass_plant %>% 
  full_join(pop_csv_n1,by=c("time", "geo_code"))

biomass_plant <- biomass_plant[!(biomass_plant$geo_code=="NA"),]

biomass_plant$value_per_capita <- biomass_plant$value / biomass_plant$mean_population
# units= 1000 T of dry matter/person
biomass_plant$value_per_capita <- biomass_plant$value_per_capita*1000

#Order by alphabet 
biomass_plant <- biomass_plant[order(biomass_plant$geo_code),]
biomass_plant <- biomass_plant[-c(6:9)]

# Only consider the years and countries for which there is data
biomass_plant <- biomass_plant %>%
  filter(value_per_capita != "NA") 

# - 2.3.a.1 Biomass production in EU from primary production sectors (agriculture, forests, fisheries, algae, waste)
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Missing data

# - 3.1.a.1 - Domestic Material Consumption (Biomass) per capita - Thousand tonnes (1000T)
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Using the eurostat already computed indicator: Tonnes/capita
# /!\ /!\ IT IS THE TOTAL MATERIALS CONSUMPTION - NOT JUST BIOMASS ! /!\ /!\
# https://ec.europa.eu/eurostat/databrowser/view/t2020_rl110/default/table?lang=en
# Material flow accounts - ENV_AC_MFA - eurostat data
# https://ec.europa.eu/eurostat/databrowser/view/env_ac_mfa/default/table?lang=en 
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
dmc_csv <- read.csv(paste0(cordir_in,"output_data/indicators/3.1.a.1/3.1.a.1_capita.csv"), stringsAsFactors = FALSE)
names(dmc_csv)
dmc_csv <- dmc_csv[-c(2)]

dmc_csv <- dmc_csv %>% 
  full_join(countries,by=c("geo"))
dmc_csv$geo_code[which(grepl("Germany",dmc_csv$geo))]  <- "DE"

dmc_csv <- dmc_csv %>%
  filter(geo != "Germany") 

levels(as.factor(dmc_csv$geo))

unique(dmc_csv$geo_code)
#Order by alphabet 
dmc_csv <- dmc_csv[order(dmc_csv$geo_code),]

# Computing the indicator/capita: (Thousand Tonnes/capita) *1000
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
mat_cons_biomass <- read.csv(paste0(cordir_in,"output_data/indicators/3.1.a.1/3.1.a.1.csv"), stringsAsFactors = FALSE)
mat_cons_biomass
names(mat_cons_biomass)
names(mat_cons_biomass)[3] <- "mat_cons_biomass"
names(mat_cons_biomass)[4] <- "unit.mat_cons_biomass"

unique(mat_cons_biomass$geo_code)
options(max.print = 1000 * ncol(mat_cons_biomass))
mat_cons_biomass <- mat_cons_biomass %>%
  filter(geo_code != "EU27_2020" & geo_code != "EU28")

levels(as.factor(mat_cons_biomass$unit.mat_cons_biomass))

#create a new column to get an intensive indicator
mat_cons_biomass <- mat_cons_biomass %>%
  full_join(pop_csv_n1,by=c("time", "geo_code"))

mat_cons_biomass <- mat_cons_biomass[!(mat_cons_biomass$geo_code=="NA"),]

mat_cons_biomass$value_per_capita <- mat_cons_biomass$mat_cons_biomass / mat_cons_biomass$mean_population
# units= 1000 T /person
mat_cons_biomass$value_per_capita <- mat_cons_biomass$value_per_capita*1000

# Use values from "value_per_capita"
names(mat_cons_biomass)[7] <- "mat_cons_biomass_capita"

# Only consider the years and countries for which there is data
mat_cons_biomass <- mat_cons_biomass %>%
  filter(value_per_capita != "NA") 
names(mat_cons_biomass)
mat_cons_biomass <- mat_cons_biomass[-c(4:6,8)]

# - 3.1.a.2 - Material footprint (Biomass) - Tonne per capita
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
mat_footprint_biom <- read.csv(paste0(cordir_in,"output_data/indicators/3.1.a.2/3.1.a.2.csv"), stringsAsFactors = FALSE) 
mat_footprint_biom
names(mat_footprint_biom)
names(mat_footprint_biom)[3] <- "mat_footprint_biom"
names(mat_footprint_biom)[4] <- "unit_mat.footprint.biom"

unique(mat_footprint_biom$geo_code)
# no EU27 nor EU28 in dataset
levels(as.factor(mat_footprint_biom$unit_mat.footprint.biom))

# - 3.1.b.1 - Energy productivity - eur/kg of oil equivalent (already intensive)
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
energy_prod <- read.csv(paste0(cordir_in, "output_data/indicators/3.1.b.1/3.1.b.1.csv"), stringsAsFactors = FALSE) 
str(energy_prod)
names(energy_prod)
names(energy_prod)[3] <- "energy_prod"
names(energy_prod)[4] <- "unit_energy_prod"

unique(energy_prod$geo_code)
options(max.print = 1000 * ncol(energy_prod))
energy_prod           <- energy_prod %>%
  filter(geo_code != "EU27_2020" & geo_code != "EU28")

levels(as.factor(energy_prod$unit_energy_prod))

# - 3.1.b.2 - Share of renewable energy in gross final energy consumption - Percent (%) (already intensive)
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
renew_energy <- read.csv(paste0(cordir_in,"output_data/indicators/3.1.b.2/3.1.b.2.csv"), stringsAsFactors = FALSE)
renew_energy
names(renew_energy)
names(renew_energy)[3] <- "renew_energy"
names(renew_energy)[4] <- "unit.renew_energy"

unique(renew_energy$geo_code)
options(max.print = 1100 * ncol(renew_energy))
renew_energy           <- renew_energy %>%
  filter(geo_code != "EU27_2020" & geo_code != "EU28")

levels(as.factor(renew_energy$unit.renew_energy))

# - 3.1.c.2 - Circular material rate - percent (% of total material use) (already intensive)
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
circ_mat_rate <- read.csv(paste0(cordir_in,"output_data/indicators/3.1.c.2/3.1.c.2.csv"), stringsAsFactors = FALSE)
circ_mat_rate
names(circ_mat_rate)
names(circ_mat_rate)[3] <- "circ_mat_rate"
names(circ_mat_rate)[4] <- "unit.circ_mat_rate"

unique(circ_mat_rate$geo_code)
options(max.print = 1100 * ncol(circ_mat_rate))
circ_mat_rate           <- circ_mat_rate %>%
  filter(geo_code != "EU27_2020" & geo_code != "EU28")

levels(as.factor(circ_mat_rate$unit.circ_mat_rate))

# - 3.4.a.2 - Total biomass consumed for energy - 1000 T of Dry Matter/capita *1000 
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
biom_energy <- read.csv(paste0(cordir_in,"output_data/indicators/3.4.a.2/3.4.a.2.csv"), stringsAsFactors = FALSE)
biom_energy
names(biom_energy)
names(biom_energy)[3] <- "biom_energy"
names(biom_energy)[4] <- "unit.biom_energy"

unique(biom_energy$geo_code)
options(max.print = 1100 * ncol(biom_energy))
biom_energy           <- biom_energy %>%
  filter(geo_code != "EU28")

levels(as.factor(biom_energy$unit.biom_energy))

#create a new column to get an intensive indicator
biom_energy <- biom_energy %>% 
  full_join(pop_csv_n1,by=c("time", "geo_code"))

biom_energy <- biom_energy[!(biom_energy$geo_code=="NA"),]

biom_energy$value_per_capita <- biom_energy$biom_energy / biom_energy$mean_population
# units= 1000 T of Dry Matter /person
biom_energy$value_per_capita <- biom_energy$value_per_capita*1000

# Use values from "value_per_capita"
names(biom_energy)[7] <- "biom_energy_capita"
#Order by alphabet 
biom_energy <- biom_energy[order(biom_energy$geo_code),]
names(biom_energy)
biom_energy <- biom_energy[-c(5:8)]

# Only consider the years and countries for which there is data
biom_energy <- biom_energy %>%
  filter(value_per_capita != "NA") 

# - 3.4.a.3 - Total biomass consumed for materials - (1000 T of Dry Matter/capita) *1000
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
biom_mat <- read.csv(paste0(cordir_in,"output_data/indicators/3.4.a.3/3.4.a.3.csv"), stringsAsFactors = FALSE)
biom_mat
names(biom_mat)
names(biom_mat)[3] <- "biom_mat"
names(biom_mat)[4] <- "unit.biom_mat"

unique(biom_mat$geo_code)
options(max.print = 1100 * ncol(biom_mat))
biom_mat           <- biom_mat %>%
  filter(geo_code != "EU28")

levels(as.factor(biom_mat$unit.biom_mat))

#create a new column to get an intensive indicator
biom_mat <- biom_mat %>% 
  full_join(pop_csv_n1,by=c("time", "geo_code"))

biom_mat <- biom_mat[!(biom_mat$geo_code=="NA"),]

biom_mat$value_per_capita <- biom_mat$biom_mat / biom_mat$mean_population
# units= 1000 T of Dry Matter /person
# if we multiply by 1000 -> Megatonne /capita
biom_mat$value_per_capita <- biom_mat$value_per_capita*1000

# Use values from "value_per_capita"
names(biom_mat)[7] <- "biom_mat_capita"
#Order by alphabet 
biom_mat <- biom_mat[order(biom_mat$geo_code),]
biom_mat <- biom_mat[-c(5:8)]

# Only consider the years and countries for which there is data
biom_mat <- biom_mat %>%
  filter(value_per_capita != "NA") 

# - 5.6.c.1 - Share biomass uses by primary sector
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# redundant with the previous - if no data, we drop it

# - 3.1.c.3 - Final Energy Consumption from renewable municipal waste
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Sarah M. follow up needed

# - 3.1.c.4 - Recycling rate of bio-waste - Kilograms per capita
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Using data from eurostat "recycling of biowaste"
# https://ec.europa.eu/eurostat/databrowser/view/CEI_WM030__custom_354910/bookmark/table?lang=en&bookmarkId=fc05c670-a84a-4ba6-8f61-90eefd9ad363 
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_csv           <- read.csv(paste0(cordir_in,"output_data/indicators/3.1.c.4/3.1.c.4_capita.csv"), stringsAsFactors = FALSE)
names(waste_csv)

waste_csv <- waste_csv %>% 
  full_join(countries,by=c("geo"))
waste_csv$geo_code[which(grepl("Germany",waste_csv$geo))]  <- "DE"

waste_csv <- waste_csv %>%
  filter(geo != "Germany") 

unique(waste_csv$geo_code)
#Order by alphabet 
waste_csv <- waste_csv[order(waste_csv$geo_code),]

# - 3.1.c.5 - Biowaste generated by source - (kg_dry/capita) * 1000
# Legend for the waste category codes 
# https://github.com/xapple/waste_flow/blob/master/waste_flow/extra_data_csv/waste_to_full_name.csv
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen <- read.csv(paste0(cordir_in,"output_data/indicators/3.1.c.5/test_long.csv"), stringsAsFactors = FALSE)
head(waste_gen)
names(waste_gen)
waste_gen <- waste_gen[-c(1)]
names(waste_gen)
names(waste_gen)[1] <- "geo_code"
names(waste_gen)[2] <- "time"
names(waste_gen)[6] <- "value"

unique(waste_gen$geo_code)

waste_gen <- waste_gen %>% 
  full_join(countries,by=c("geo_code"))

levels(as.factor(waste_gen$geo))

waste_gen           <- waste_gen %>%
  filter(geo_code != "EU27_2020" & geo_code != "EU28" & geo != "NA")
levels(as.factor(waste_gen$geo_code))

# Select the values which correspond to the indicator
# Biowaste generated=Disposal => https://github.com/xapple/waste_flow/blob/master/waste_flow/extra_data_csv/treatment_to_full_name.csv

levels(as.factor(waste_gen$wst_oper))

waste_gen           <- waste_gen %>%
  filter(wst_oper != "RCV_E" & wst_oper != "RCV_R_B")

#create a new column to get an intensive indicator
waste_gen <- waste_gen %>% 
  full_join(pop_csv_n1,by=c("time", "geo_code"))

names(waste_gen)
waste_gen <- waste_gen[-c(8:12)]

waste_gen <- waste_gen[!(waste_gen$geo_code=="NA"),]

waste_gen$value_per_capita <- waste_gen$value / waste_gen$mean_population
#waste_gen$value_per_capita <- waste_gen$value_per_capita*1000

#Order by alphabet 
waste_gen <- waste_gen[order(waste_gen$geo_code),]
names(waste_gen)

levels(as.factor(waste_gen$category))
waste_gen_household <- waste_gen %>% filter(category %in% c("household"))
waste_gen_industrial<- waste_gen %>% filter(category %in% c("industrial"))

# Get data by category and by source : household (category)
# Paper and cardboard wastes = W072_hh           (source)
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_hh_paper <- waste_gen_household %>% filter(waste %in% c("W072_hh"))

waste_gen_hh_paper <- waste_gen_hh_paper %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

#necessary? What are the units then?
#waste_gen_hh_paper$value_per_capita <- waste_gen_hh_paper$value_per_capita*1000

# Untreated wood = W075_hh
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_hh_wood <- waste_gen_household %>% filter(waste %in% c("W075_hh"))

waste_gen_hh_wood <- waste_gen_hh_wood %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Food waste = W091_hh
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_hh_food <- waste_gen_household %>% filter(waste %in% c("W091_hh"))

waste_gen_hh_food <- waste_gen_hh_food %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Green waste = W092_hh
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_hh_green <- waste_gen_household %>% filter(waste %in% c("W092_hh"))

waste_gen_hh_green <- waste_gen_hh_green %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Textiles, leather and rubber = W7376_hh
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_hh_text <- waste_gen_household %>% filter(waste %in% c("W7376_hh"))

waste_gen_hh_text <- waste_gen_hh_text %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Composites, human hygiene waste (diapers, tampons, condoms, etc.) = W9999_hh
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_hh_compo <- waste_gen_household %>% filter(waste %in% c("W9999_hh"))

waste_gen_hh_compo <- waste_gen_hh_compo %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Get data by category and by source : industrial (category)
# Paper and cardboard wastes = W072_ind           (source)
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_ind_paper <- waste_gen_industrial %>% filter(waste %in% c("W072_ind"))

waste_gen_ind_paper <- waste_gen_ind_paper %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Rubber wastes = W073_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_ind_rubber <- waste_gen_industrial %>% filter(waste %in% c("W073_ind"))

waste_gen_ind_rubber <- waste_gen_ind_rubber %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Wood wastes = W075_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_ind_wood <- waste_gen_industrial %>% filter(waste %in% c("W075_ind"))

waste_gen_ind_wood <- waste_gen_ind_wood %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Textile wastes = W076_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_ind_textile <- waste_gen_industrial %>% filter(waste %in% c("W076_ind"))

waste_gen_ind_textile <- waste_gen_ind_textile %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Animal and mixed food waste = W091_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_ind_animal <- waste_gen_industrial %>% filter(waste %in% c("W091_ind"))

waste_gen_ind_animal <- waste_gen_ind_animal %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Vegetal wastes = W092_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_ind_vegetal <- waste_gen_industrial %>% filter(waste %in% c("W092_ind"))

waste_gen_ind_vegetal <- waste_gen_ind_vegetal %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Animal feces, urine and manure = W093_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_gen_ind_manure <- waste_gen_industrial %>% filter(waste %in% c("W093_ind"))

waste_gen_ind_manure <- waste_gen_ind_manure %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# - 3.1.c.6 - Biowaste recovered by source - Kg_dry/capita * 1000
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov <- read.csv(paste0(cordir_in,"output_data/indicators/3.1.c.5/test_long.csv"), stringsAsFactors = FALSE)
head(waste_recov)
names(waste_recov)
waste_recov <- waste_recov[-c(1)]
names(waste_recov)
names(waste_recov)[1] <- "geo_code"
names(waste_recov)[2] <- "time"
names(waste_recov)[6] <- "value"

unique(waste_recov$geo_code)

waste_recov <- waste_recov %>% 
  full_join(countries,by=c("geo_code"))

levels(as.factor(waste_recov$geo))

waste_recov           <- waste_recov %>%
  filter(geo_code != "EU27_2020" & geo_code != "EU28" & geo != "NA")
levels(as.factor(waste_recov$geo_code))

# Select the values which correspond to the indicator
# Biowaste recovered=recovery => https://github.com/xapple/waste_flow/blob/master/waste_flow/extra_data_csv/treatment_to_full_name.csv

levels(as.factor(waste_recov$wst_oper))

waste_recov           <- waste_recov %>%
  filter(wst_oper != "DSP_I" & wst_oper != "DSP_L" & wst_oper != "DSP_OTH")

#create a new column to get an intensive indicator
waste_recov <- waste_recov %>% 
  full_join(pop_csv_n1,by=c("time", "geo_code"))

names(waste_recov)
waste_recov <- waste_recov[-c(8:12)]

waste_recov <- waste_recov[!(waste_recov$geo_code=="NA"),]

waste_recov$value_per_capita <- waste_recov$value / waste_recov$mean_population
#waste_recov$value_per_capita <- waste_recov$value_per_capita*1000

#Order by alphabet 
waste_recov <- waste_recov[order(waste_recov$geo_code),]
names(waste_recov)

levels(as.factor(waste_recov$category))
waste_recov_household <- waste_recov %>% filter(category %in% c("household"))
waste_recov_industrial<- waste_recov %>% filter(category %in% c("industrial"))

# Get data by category and by source : household (category)
# Paper and cardboard wastes = W072_hh           (source)
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_hh_paper <- waste_recov_household %>% filter(waste %in% c("W072_hh"))

waste_recov_hh_paper <- waste_recov_hh_paper %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Untreated wood = W075_hh
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_hh_wood <- waste_recov_household %>% filter(waste %in% c("W075_hh"))

waste_recov_hh_wood <- waste_recov_hh_wood %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Food waste = W091_hh
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_hh_food <- waste_recov_household %>% filter(waste %in% c("W091_hh"))

waste_recov_hh_food <- waste_recov_hh_food %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Green waste = W092_hh
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_hh_green <- waste_recov_household %>% filter(waste %in% c("W092_hh"))

waste_recov_hh_green <- waste_recov_hh_green %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Textiles, leather and rubber = W7376_hh
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_hh_text <- waste_recov_household %>% filter(waste %in% c("W7376_hh"))

waste_recov_hh_text <- waste_recov_hh_text %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Composites, human hygiene waste (diapers, tampons, condoms, etc.) = W9999_hh
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_hh_compo <- waste_recov_household %>% filter(waste %in% c("W9999_hh"))

waste_recov_hh_compo <- waste_recov_hh_compo %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Get data by category and by source : industrial (category)
# Paper and cardboard wastes = W072_ind           (source)
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_ind_paper <- waste_recov_industrial %>% filter(waste %in% c("W072_ind"))

waste_recov_ind_paper <- waste_recov_ind_paper %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Rubber wastes = W073_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_ind_rubber <- waste_recov_industrial %>% filter(waste %in% c("W073_ind"))

waste_recov_ind_rubber <- waste_recov_ind_rubber %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Wood wastes = W075_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_ind_wood <- waste_recov_industrial %>% filter(waste %in% c("W075_ind"))

waste_recov_ind_wood <- waste_recov_ind_wood %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Textile wastes = W076_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_ind_textile <- waste_recov_industrial %>% filter(waste %in% c("W076_ind"))

waste_recov_ind_textile <- waste_recov_ind_textile %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Animal and mixed food waste = W091_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_ind_animal <- waste_recov_industrial %>% filter(waste %in% c("W091_ind"))

waste_recov_ind_animal <- waste_recov_ind_animal %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Vegetal wastes = W092_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_ind_vegetal <- waste_recov_industrial %>% filter(waste %in% c("W092_ind"))

waste_recov_ind_vegetal <- waste_recov_ind_vegetal %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# Animal feces, urine and manure = W093_ind
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
waste_recov_ind_manure <- waste_recov_industrial %>% filter(waste %in% c("W093_ind"))

waste_recov_ind_manure <- waste_recov_ind_manure %>%
  filter(value_per_capita != "NA" & value_per_capita != "0")

# - 3.4.b.1 Liquid biofuels production (bioethanol, pure biogasoline, biodiesel, bio jet kerosene and other liquid biofuels) 
# - Thousand tonnes per year / capita *1000
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
biofuels_csv           <- read.csv(paste0(cordir_in,"output_data/indicators/3.4.b.1/3.4.b.1.csv"), stringsAsFactors = FALSE)
names(biofuels_csv)
names(biofuels_csv)[2] <- "geo"

biofuels_csv <- biofuels_csv %>% 
  full_join(countries,by=c("geo"))
biofuels_csv$geo_code[which(grepl("Germany",biofuels_csv$geo))]  <- "DE"

biofuels_csv <- biofuels_csv %>%
  filter(geo != "Germany") 

unique(biofuels_csv$geo_code)
# Only consider the years and countries for which there is data
biofuels_csv <- biofuels_csv %>%
  filter(geo_code != "NA") 
#Order by alphabet 
biofuels_csv <- biofuels_csv[order(biofuels_csv$geo_code),]

names(biofuels_csv)
levels(as.factor(biofuels_csv$TIME))
levels(as.factor(biofuels_csv$SIEC))
levels(as.factor(biofuels_csv$PLANT_TEC))
levels(as.factor(biofuels_csv$UNIT))
levels(as.factor(biofuels_csv$Flag.and.Footnotes))

biofuels_csv <- biofuels_csv[-c(4,7)]
names(biofuels_csv)[1] <- "time"
names(biofuels_csv)[3] <- "type"
names(biofuels_csv)[4] <- "unit"
names(biofuels_csv)[5] <- "value_SIEC"

#create a new column to get an intensive indicator
biofuels_csv$value <- as.numeric(gsub(",","",biofuels_csv$value))

biofuels_csv <- biofuels_csv %>%
  full_join(pop_csv_n1,by=c("time", "geo_code"))

biofuels_csv <- biofuels_csv[!(biofuels_csv$mean_population=="NA"),]

biofuels_csv$value_per_capita <- biofuels_csv$value / biofuels_csv$mean_population
biofuels_csv$value_per_capita <- biofuels_csv$value_per_capita*1000

biofuels_csv <- biofuels_csv[-c(7:11)]

# there are several levels of the factors, specified in the "unit" column
levels(as.factor(biofuels_csv$type))

biofuels_other_liquid <- biofuels_csv %>% filter(type %in% c("Other liquid biofuels"))
biofuels_kerosene     <- biofuels_csv %>% filter(type %in% c("Pure bio jet kerosene"))
biofuels_biodiesel    <- biofuels_csv %>% filter(type %in% c("Pure biodiesels"))
biofuels_biogasoline  <- biofuels_csv %>% filter(type %in% c("Pure biogasoline"))

# - 3.4.b.2 Biogasses (indigenous) production - TERAJOULE/capita *1000
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
biogas_csv            <- read.csv(paste0(cordir_in,"output_data/indicators/3.4.b.2/3.4.b.2.csv"), stringsAsFactors = FALSE)
names(biogas_csv)
names(biogas_csv)[2] <- "geo"

biogas_csv <- biogas_csv %>% 
  full_join(countries,by=c("geo"))
biogas_csv$geo_code[which(grepl("Germany",biogas_csv$geo))]  <- "DE"

biogas_csv <- biogas_csv %>%
  filter(geo != "Germany") 

unique(biogas_csv$geo_code)
# Only consider the years and countries for which there is data
biogas_csv <- biogas_csv %>%
  filter(geo_code != "NA") 

#Order by alphabet 
biogas_csv <- biogas_csv[order(biogas_csv$geo_code),]
names(biogas_csv)

levels(as.factor(biogas_csv$NRG_BAL))
levels(as.factor(biogas_csv$SIEC))
levels(as.factor(biogas_csv$Flag.and.Footnotes))

biogas_csv           <- biogas_csv[-c(3,7)]
names(biogas_csv)[1] <- "time"
names(biogas_csv)[3] <- "type"
names(biogas_csv)[4] <- "unit"
names(biogas_csv)[5] <- "value_SIEC"

#create a new column to get an intensive indicator
biogas_csv$value <- as.numeric(gsub(",","",biogas_csv$value))

biogas_csv <- biogas_csv %>%
  full_join(pop_csv_n1,by=c("time", "geo_code"))

biogas_csv <- biogas_csv[!(biogas_csv$mean_population=="NA"),]

biogas_csv$value_per_capita <- biogas_csv$value / biogas_csv$mean_population
biogas_csv$value_per_capita <- biogas_csv$value_per_capita*1000

biogas_csv <- biogas_csv[-c(7:11)]

# there are several levels of the factors, specified in the "unit" column
levels(as.factor(biogas_csv$type))

biogas_biogas         <- biogas_csv %>% filter(type %in% c("Biogases"))
biogas_geothermal     <- biogas_csv %>% filter(type %in% c("Geothermal"))
biogas_solid_biofuels <- biogas_csv %>% filter(type %in% c("Primary solid biofuels"))
biogas_waste          <- biogas_csv %>% filter(type %in% c("Renewable municipal waste"))
biogas_solar          <- biogas_csv %>% filter(type %in% c("Solar thermal"))
